# Generated by Django 4.1.2 on 2022-11-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finImg", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="ImageFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mainImage", models.ImageField(upload_to="")),
                ("keywords", models.TextField()),
                ("url1", models.TextField()),
                ("url2", models.TextField()),
                ("url3", models.TextField()),
                ("url4", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="KeywordPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Weather",
                    models.CharField(
                        choices=[
                            ("Cloudy", "Cloudy"),
                            ("Sunny", "Sunny"),
                            ("Snowy", "Snowy"),
                            ("Rainy", "Rainy"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Drawing",
                    models.CharField(
                        choices=[
                            ("Digital Art", "Digital Art"),
                            ("Sketched", "Sketched"),
                            ("Impressionism", "Impressionism"),
                            ("Oil and Canvas", "Oil and Canvas"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Emotion",
                    models.CharField(
                        choices=[
                            ("Angry", "Angry"),
                            ("Cheerful", "Cheerful"),
                            ("Depressed", "Depressed"),
                            ("Happy", "Happy"),
                            ("Neutral", "Neutral"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("content1", models.TextField(max_length=7)),
                ("content2", models.TextField(max_length=7)),
                ("content3", models.TextField(max_length=7)),
                ("create_dat", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Weather",
                    models.CharField(
                        choices=[
                            ("비", "Rainy"),
                            ("흐림", "Cloudy"),
                            ("맑음", "Sunny"),
                            ("눈", "Snowy"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Drawing",
                    models.CharField(
                        choices=[
                            ("MZ세대 스타일", "Vaper Wave"),
                            ("스케치", "Sketched"),
                            ("인상주의", "Impressionism"),
                            ("디지털 아트", "Digital Art"),
                            ("유화", "Oil and Canvas"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Emotion",
                    models.CharField(
                        choices=[
                            ("보통", "Neutral"),
                            ("기쁨", "Happy"),
                            ("우울", "Depressed"),
                            ("쾌활", "Cheerful"),
                            ("화남", "Angry"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={"ordering": ["-id"],},
        ),
    ]
