# Generated by Django 4.1.2 on 2022-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_alter_memory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="blog/images/%Y/%m/%d/"),
        ),
    ]
