# Generated by Django 4.1.2 on 2022-11-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_memory_head_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="content",
            field=models.TextField(max_length=1000),
        ),
    ]
