# Generated by Django 4.1.2 on 2022-11-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_alter_memory_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory", name="title", field=models.CharField(max_length=30),
        ),
    ]
