# Generated by Django 4.1.2 on 2022-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_alter_memory_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Weather",
                    models.CharField(
                        choices=[
                            ("Cloudy", "흐려요"),
                            ("Snowy", "눈이 와요"),
                            ("Rainy", "비가 와요"),
                            ("Sunny", "맑아요"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "Drawing",
                    models.CharField(
                        choices=[
                            ("Sketched", "스케치"),
                            ("Oil and Canvas", "유화"),
                            ("Impressionism", "인상주의"),
                            ("Digital Art", "디지털 아트"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("content1", models.TextField(max_length=7)),
                ("content2", models.TextField(max_length=7)),
                ("content3", models.TextField(max_length=7)),
                ("create_dat", models.DateTimeField(auto_now_add=True)),
                ("update_dat", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
