# Generated by Django 4.1.2 on 2022-11-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0006_keywordpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="keywordpost",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("Sunny", "맑아요"),
                    ("Rainy", "비가 와요"),
                    ("Cloudy", "흐려요"),
                    ("Snowy", "눈이 와요"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Oil and Canvas", "유화"),
                    ("Impressionism", "인상주의"),
                    ("Sketched", "스케치"),
                    ("Digital Art", "디지털 아트"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("Sunny", "맑아요"),
                    ("Rainy", "비가 와요"),
                    ("Cloudy", "흐려요"),
                    ("Snowy", "눈이 와요"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("Sunny", "맑아요"),
                    ("Rainy", "비가 와요"),
                    ("Cloudy", "흐려요"),
                    ("Snowy", "눈이 와요"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Oil and Canvas", "유화"),
                    ("Impressionism", "인상주의"),
                    ("Sketched", "스케치"),
                    ("Digital Art", "디지털 아트"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("Sunny", "맑아요"),
                    ("Rainy", "비가 와요"),
                    ("Cloudy", "흐려요"),
                    ("Snowy", "눈이 와요"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
