# Generated by Django 4.1.2 on 2022-11-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0007_keywordpost_emotion_memory_drawing_memory_emotion_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="memory", name="title",),
        migrations.AddField(
            model_name="keywordpost",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="blog/images/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Sketched", "스케치"),
                    ("Impressionism", "인상주의"),
                    ("Oil and Canvas", "유화"),
                    ("Digital Art", "디지털 아트"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Sketched", "스케치"),
                    ("Impressionism", "인상주의"),
                    ("Oil and Canvas", "유화"),
                    ("Digital Art", "디지털 아트"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
