# Generated by Django 4.1.2 on 2022-11-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0008_remove_memory_title_keywordpost_head_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Oil and Canvas", "Oil and Canvas"),
                    ("Digital Art", "Digital Art"),
                    ("Sketched", "Sketched"),
                    ("Impressionism", "Impressionism"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("Rainy", "Rainy"),
                    ("Snowy", "Snowy"),
                    ("Cloudy", "Cloudy"),
                    ("Sunny", "Sunny"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("Rainy", "Rainy"),
                    ("Snowy", "Snowy"),
                    ("Cloudy", "Cloudy"),
                    ("Sunny", "Sunny"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Digital Art", "디지털 아트"),
                    ("Oil and Canvas", "유화"),
                    ("Impressionism", "인상주의"),
                    ("Sketched", "스케치"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("Snowy", "눈이 와요"),
                    ("Cloudy", "흐려요"),
                    ("Rainy", "비가 와요"),
                    ("Sunny", "맑아요"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("Snowy", "눈이 와요"),
                    ("Cloudy", "흐려요"),
                    ("Rainy", "비가 와요"),
                    ("Sunny", "맑아요"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
