# Generated by Django 4.1.2 on 2022-11-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0010_alter_keywordpost_drawing_alter_keywordpost_emotion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Sketched", "Sketched"),
                    ("Impressionism", "Impressionism"),
                    ("Oil and Canvas", "Oil and Canvas"),
                    ("Digital Art", "Digital Art"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("Cheerful", "Cheerful"),
                    ("Happy", "Happy"),
                    ("Depressed", "Depressed"),
                    ("Neutral", "Neutral"),
                    ("Angry", "Angry"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("Rainy", "Rainy"),
                    ("Snowy", "Snowy"),
                    ("Sunny", "Sunny"),
                    ("Cloudy", "Cloudy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="content1",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="content2",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="content3",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Sketched", "Sketched"),
                    ("Impressionism", "Impressionism"),
                    ("Oil and Canvas", "Oil and Canvas"),
                    ("Digital Art", "Digital Art"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("Cheerful", "Cheerful"),
                    ("Happy", "Happy"),
                    ("Depressed", "Depressed"),
                    ("Neutral", "Neutral"),
                    ("Angry", "Angry"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("Rainy", "Rainy"),
                    ("Snowy", "Snowy"),
                    ("Sunny", "Sunny"),
                    ("Cloudy", "Cloudy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
