# Generated by Django 4.1.2 on 2022-11-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0013_alter_keywordpost_drawing_alter_keywordpost_emotion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("인상주의", "Impressionism"),
                    ("디지털 아트", "Digital Art"),
                    ("유화", "Oil and Canvas"),
                    ("스케치", "Sketched"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("보통", "Neutral"),
                    ("쾌활", "Cheerful"),
                    ("우울", "Depressed"),
                    ("화남", "Angry"),
                    ("기쁨", "Happy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("눈", "Snowy"),
                    ("맑음", "Sunny"),
                    ("비", "Rainy"),
                    ("흐림", "Cloudy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("인상주의", "Impressionism"),
                    ("디지털 아트", "Digital Art"),
                    ("유화", "Oil and Canvas"),
                    ("스케치", "Sketched"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("보통", "Neutral"),
                    ("쾌활", "Cheerful"),
                    ("우울", "Depressed"),
                    ("화남", "Angry"),
                    ("기쁨", "Happy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("눈", "Snowy"),
                    ("맑음", "Sunny"),
                    ("비", "Rainy"),
                    ("흐림", "Cloudy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
