# Generated by Django 4.1.2 on 2022-11-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0017_alter_keywordpost_drawing_alter_keywordpost_emotion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finImg", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="ImageFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mainImage", models.ImageField(upload_to="")),
                ("keywords", models.TextField()),
                ("url1", models.TextField()),
                ("url2", models.TextField()),
                ("url3", models.TextField()),
                ("url4", models.TextField()),
            ],
        ),
        migrations.RemoveField(model_name="keywordpost", name="head_image",),
        migrations.RemoveField(model_name="memory", name="head_image",),
        migrations.AlterField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("MZ세대 스타일", "Vaper Wave"),
                    ("스케치", "Sketched"),
                    ("유화", "Oil and Canvas"),
                    ("인상주의", "Impressionism"),
                    ("디지털 아트", "Digital Art"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("기쁨", "Happy"),
                    ("우울", "Depressed"),
                    ("보통", "Neutral"),
                    ("쾌활", "Cheerful"),
                    ("화남", "Angry"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Weather",
            field=models.CharField(
                choices=[("눈", "눈"), ("비", "비"), ("맑음", "맑음"), ("흐림", "흐림")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("MZ세대 스타일", "Vaper Wave"),
                    ("스케치", "Sketched"),
                    ("유화", "Oil and Canvas"),
                    ("인상주의", "Impressionism"),
                    ("디지털 아트", "Digital Art"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("기쁨", "Happy"),
                    ("우울", "Depressed"),
                    ("보통", "Neutral"),
                    ("쾌활", "Cheerful"),
                    ("화남", "Angry"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Weather",
            field=models.CharField(
                choices=[("눈", "눈"), ("비", "비"), ("맑음", "맑음"), ("흐림", "흐림")],
                max_length=20,
                null=True,
            ),
        ),
    ]
