# Generated by Django 4.1.2 on 2022-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0020_alter_keywordpost_drawing_alter_keywordpost_emotion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("인상주의", "Impressionism"),
                    ("요즘 스타일", "Vaper Wave"),
                    ("스케치", "Sketched"),
                    ("유화", "Oil and Canvas"),
                    ("디지털 아트", "Digital Art"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("기쁨", "Happy"),
                    ("우울", "Depressed"),
                    ("쾌활", "Cheerful"),
                    ("화남", "Angry"),
                    ("보통", "Neutral"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Weather",
            field=models.CharField(
                choices=[("비", "비"), ("맑음", "맑음"), ("눈", "눈"), ("흐림", "흐림")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("인상주의", "Impressionism"),
                    ("요즘 스타일", "Vaper Wave"),
                    ("스케치", "Sketched"),
                    ("유화", "Oil and Canvas"),
                    ("디지털 아트", "Digital Art"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("기쁨", "Happy"),
                    ("우울", "Depressed"),
                    ("쾌활", "Cheerful"),
                    ("화남", "Angry"),
                    ("보통", "Neutral"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Weather",
            field=models.CharField(
                choices=[("비", "비"), ("맑음", "맑음"), ("눈", "눈"), ("흐림", "흐림")],
                max_length=20,
                null=True,
            ),
        ),
    ]
